### ISSUE TITLE
StructureMap and Orleans

### ISSUE THREAD

**Issue by misha-fm** [dotnet/orleans#4442]
Hi! I try to integrate the StructureMap in Orleans (v 2.0.0).

I use the following code:

```cs
var builder = new SiloHostBuilder()
    .UseServiceProviderFactory(new StructureMapServiceProviderFactory(new MyRegistry());
```

`StructureMapServiceProviderFactory` implements a method:
```cs
public Registry CreateBuilder(IServiceCollection services)
{
    var registry = Registry ?? new Registry();
    registry.Populate(services);
    return registry;
}
```

But call to `registry.Populate(services)` throws an exception:
"Specified argument was out of the range of valid values.
Parameter name: Orleans.Runtime.StatelessWorkerPlacement must have at least one public constructor to be plugged in by StructureMap".

So, what is the correct way to inject StructureMap into Orleans DI framework?

**Comment by xiazen** [comment]
which structure map nugget are you using?

I found this https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection on the internet show me install `StructureMap.Microsoft.DependencyInjection` and then it has a sample showing how to plug StructureMap into ASP.NET DI abstraction, which is the abstraction Orleans integrated with. This seems to be the suggested way if user want to configure third party DI container  to use with ASP.NET DI abstractions. is this what you are using? your code doesn't look quite like the sample .

**Comment by misha-fm** [comment]
Hi, @xiazen! Thank you for your reply!
Yes, I'm using that Nuget (StructureMap.Microsoft.DependencyInjection), and the code for method `CreateBuilder` I took from there. According to https://github.com/aspnet/DependencyInjection/issues/442, all implementations are populating Orleans services into the container: `registry.Populate(services);`. But as I wrote in my first post, it throws the exception saying that `Orleans.Runtime.StatelessWorkerPlacement` must have a public constructor in order to be plugged into the StructureMap container.

Tried to use Autofac in a similar manner: 
```cs
var autofacSpFactory = new AutofacServiceProviderFactory();
var builder = new SiloHostBuilder()
	.UseLocalhostClustering()
	.UseServiceProviderFactory(autofacSpFactory);
```

It throws the similar exception: "No accessible constructors were found for the type 'Orleans.Runtime.StatelessWorkerPlacement'."

StackTrace:
```cs
   at Autofac.Core.Activators.Reflection.DefaultConstructorFinder.GetDefaultPublicConstructors(Type type)
   at Autofac.Core.Activators.Reflection.ReflectionActivator..ctor(Type implementationType, IConstructorFinder constructorFinder, IConstructorSelector constructorSelector, IEnumerable`1 configuredParameters, IEnumerable`1 configuredProperties)
   at Autofac.Builder.ConcreteReflectionActivatorData.get_Activator()
   at Autofac.Builder.RegistrationBuilder.CreateRegistration[TLimit,TActivatorData,TSingleRegistrationStyle](IRegistrationBuilder`3 builder)
   at Autofac.Builder.RegistrationBuilder.RegisterSingleComponent[TLimit,TActivatorData,TSingleRegistrationStyle](IComponentRegistry cr, IRegistrationBuilder`3 builder)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Orleans.Hosting.ServiceProviderFactoryAdapter`1.BuildServiceProvider(HostBuilderContext context, IServiceCollection services)
   at Orleans.Hosting.ServiceProviderBuilder.BuildServiceProvider(HostBuilderContext context)
   at Orleans.Hosting.SiloHostBuilder.Build()
   at CoreLedger.Orleans.Host.CoreLedgerSilo.<StartSilo>d__8.MoveNext() in C:\Users\Mikhail PC\source\Workspaces\Coreledger Core\Dev\OrleansSilo\src\CoreLedger.Orleans.Host\CoreLedgerSilo.cs:line 183
```

**Comment by misha-fm** [comment]
Another option to inject a StructureMap is to provide a factory-lambda in `UseServiceProviderFactory` method:
```cs
var builder = new SiloHostBuilder()
	.UseServiceProviderFactory(services =>
	{
		var ctr = new Container();
		ctr.Populate(services);
		return ctr.GetInstance<IServiceProvider>();
	})
```

But it throws the same excepotion after calling to `popalate` method.

**Comment by xiazen** [comment]
my wild guess is StructureMap requires everything injected into DI has a public constructor, which StatelessWorkerPlacement doesn't... it wasn't a problem with the native ASP.NET DI solution we uses, so we never run into this issue before.  you are more familair with StructureMap than I'm, is this the case? if yes, Orleans may need to made code change for third party DI container like StructureMap to be integrated with Orleans.

**Comment by xiazen** [comment]
at the same time  I will look into StructureMap. Just you are more familair with it supposeblely, so I figured I can just ask.

**Comment by misha-fm** [comment]
yeah, you're right - StructureMap does require that all services it tries to instantiate need public constructors. when I have some spare time, I'll also try to investigate the way how Orleans could support this behaviour

**Comment by xiazen** [comment]
submitted pr #4453 which seems to fix the issue.

**Comment by misha-fm** [comment]
Great, thank you! Hope this feel fix the issue. Waiting for a new release!

**Comment by sergeybykov** [comment]
Resolved via #4453.

**Comment by stephenlautier** [comment]
@sergeybykov was this released in `2.0.3`? From the changes, this seems to be in `Microsoft.Orleans.Core.Abstractions`, however, there is no 2.0.3 for the specified package; furthermore, I had updated to 2.0.3 but its still not working

**Comment by ReubenBond** [comment]
@stephenlautier yes, this should be fixed in 2.0.3 - we made a change to fix it without having to revise the Abstractions package
