### ISSUE TITLE
Two activations for the same id on a stable cluster

### ISSUE THREAD

**Issue by MaximTkachenko** [dotnet/orleans#9855]
Environment: 
- Orleans 9.2.1
- 10 silos
- hosted in kubernetes
- cassandra reminders
- azure table storage clustering
- kubernetes integration

In rare cases, I see two activations for the same ID even though the cluster has been stable for hours. I have an HTTP endpoint that returns the pod name and an activation’s creation time:
```
# curl "http://api.app.svc.cluster.local/objects/AAA111/debug"
{"podName":"app-5547f98bdc-x5q4z","createdAt":"2025-12-24T14:33:36.6360447Z"}
# curl "http://api.app.svc.cluster.local/objects/AAA111/debug"
{"podName":"app-5547f98bdc-x5q4z","createdAt":"2025-12-24T14:33:36.6360447Z"}
# curl "http://api.app.svc.cluster.local/objects/AAA111/debug"
{"podName":"app-5547f98bdc-kc24d","createdAt":"2025-12-24T14:33:24.3069423Z"}
# curl "http://api.app.svc.cluster.local/objects/AAA111/debug"
{"podName":"app-5547f98bdc-x5q4z","createdAt":"2025-12-24T14:33:36.6360447Z"}
```

As I mentioned, this happens while the cluster remains stable for hours. Is this a known issue?

**Comment by ReubenBond** [comment]
Hi Maxim, could you provide more detail such as how the endpoint which queries activations works? Code would be useful

**Comment by MaximTkachenko** [comment]
Endpoint:
```
app.MapGet("/objects/{id}/debug", async (string id, IClusterClient clusterClient) =>
{
    var debugInfo = await clusterClient.GetGrain<IObjectGrain>(id).GetDebugInfoAsync();
    return Results.Ok(debugInfo);
});
```
In the grain class:
```
...
private readonly DateTime _created = DateTime.UtcNow;

public Task<DebugInfo> GetDebugInfoAsync()
{
    return Task.FromResult(new DebugInfo(Environment.GetEnvironmentVariable("POD_NAME"), _created));
}
...
```
I also consumed this endpoint using pods ip addresses: different pods give different results.

**Comment by ReubenBond** [comment]
Thanks for the info. Are you able to share the membership table contents either from logs or by dumping the active hosts in storage?

**Comment by MaximTkachenko** [comment]
I redeployed the cluster a couple of times. Let me reproduce it and I will add this information.

**Comment by MaximTkachenko** [comment]
Ok, found it in logs. Active only:
```
SiloAddress=S10.142.36.39:11111:125591528 SiloName=app-5547f98bdc-bh6tc Status=Active, 
SiloAddress=S10.142.33.48:11111:125591559 SiloName=app-5547f98bdc-gp6p2 Status=Active, 
SiloAddress=S10.142.33.17:11111:125591479 SiloName=app-5547f98bdc-86qfr Status=Active, 
SiloAddress=S10.142.36.79:11111:125591625 SiloName=app-5547f98bdc-np5cj Status=Active, 
SiloAddress=S10.142.33.138:11111:125591609 SiloName=app-5547f98bdc-5ch97 Status=Active, 
SiloAddress=S10.142.35.160:11111:125591496 SiloName=app-5547f98bdc-kc24d Status=Active, 
SiloAddress=S10.142.36.117:11111:125591576 SiloName=app-5547f98bdc-x5q4z Status=Active, 
SiloAddress=S10.142.33.172:11111:125591596 SiloName=app-5547f98bdc-wwkkx Status=Active, 
SiloAddress=S10.142.38.190:11111:125591544 SiloName=app-5547f98bdc-sqdtb Status=Active, 
SiloAddress=S10.142.33.93:11111:125591512 SiloName=app-5547f98bdc-8472t Status=Active, 
```

Full log record:
```
Received cluster membership snapshot via gossip: 
[Version: 5020, 81 silos, 
SiloAddress=S10.142.35.134:11111:125580314 SiloName=app-6d756f64bb-h98n6 Status=Dead, 
SiloAddress=S10.142.36.39:11111:125591528 SiloName=app-5547f98bdc-bh6tc Status=Active, 
SiloAddress=S10.142.33.179:11111:125404380 SiloName=app-5c8f976684-58gfk Status=Dead, 
SiloAddress=S10.142.35.144:11111:125510910 SiloName=app-56c9d6644c-66d58 Status=Dead, 
SiloAddress=S10.142.33.48:11111:125591559 SiloName=app-5547f98bdc-gp6p2 Status=Active, 
SiloAddress=S10.142.33.170:11111:125411006 SiloName=app-5c8f976684-q5c8p Status=Dead, 
SiloAddress=S10.142.35.197:11111:124806095 SiloName=app-5c8f976684-lvvlk Status=Dead, 
SiloAddress=S10.142.38.160:11111:125510925 SiloName=app-56c9d6644c-s6x2f Status=Dead, 
SiloAddress=S10.142.38.129:11111:125580370 SiloName=app-6d756f64bb-wm8wb Status=Dead, 
SiloAddress=S10.142.33.246:11111:125519476 SiloName=app-6cbc9f7f-xfjrz Status=Dead, 
SiloAddress=S10.142.33.102:11111:125580432 SiloName=app-6d756f64bb-svhqx Status=Dead, 
SiloAddress=S10.142.32.229:11111:124805996 SiloName=app-5c8f976684-j55ph Status=Dead, 
SiloAddress=S10.142.36.111:11111:125510980 SiloName=app-56c9d6644c-mlg87 Status=Dead, 
SiloAddress=S10.142.33.17:11111:125591479 SiloName=app-5547f98bdc-86qfr Status=Active, 
SiloAddress=S10.142.32.233:11111:125511012 SiloName=app-56c9d6644c-hcv9x Status=Dead, 
SiloAddress=S10.142.33.175:11111:125403309 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.175:11111:125403571 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.175:11111:125404109 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.175:11111:125402303 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.175:11111:125402591 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.175:11111:125402849 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.175:11111:124806114 SiloName=app-5c8f976684-22dw8 Status=Dead, 
SiloAddress=S10.142.33.185:11111:125410991 SiloName=app-5c8f976684-pqtjl Status=Dead, 
SiloAddress=S10.142.36.79:11111:125591625 SiloName=app-5547f98bdc-np5cj Status=Active, 
SiloAddress=S10.142.36.173:11111:125519509 SiloName=app-6cbc9f7f-flf24 Status=Dead, 
SiloAddress=S10.142.33.239:11111:125580386 SiloName=app-6d756f64bb-5qcff Status=Dead, 
SiloAddress=S10.142.33.183:11111:125519428 SiloName=app-6cbc9f7f-szhwp Status=Dead, 
SiloAddress=S10.142.33.166:11111:125404495 SiloName=app-5c8f976684-hh6gr Status=Dead, 
SiloAddress=S10.142.33.166:11111:125405376 SiloName=app-5c8f976684-hh6gr Status=Dead, 
SiloAddress=S10.142.33.166:11111:125405222 SiloName=app-5c8f976684-hh6gr Status=Dead, 
SiloAddress=S10.142.33.159:11111:125410901 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125410998 SiloName=app-5c8f976684-9lsmj Status=Dead, 
SiloAddress=S10.142.33.159:11111:125410361 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125410751 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125407886 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125408786 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125409199 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125405885 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125405393 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125405619 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.159:11111:125406225 SiloName=app-5c8f976684-pvcvs Status=Dead, 
SiloAddress=S10.142.33.138:11111:125591609 SiloName=app-5547f98bdc-5ch97 Status=Active, 
SiloAddress=S10.142.34.50:11111:125580297 SiloName=app-6d756f64bb-kmlck Status=Dead, 
SiloAddress=S10.142.36.234:11111:125511028 SiloName=app-56c9d6644c-jl5q8 Status=Dead, 
SiloAddress=S10.142.33.2:11111:125580282 SiloName=app-6d756f64bb-qhh7h Status=Dead, 
SiloAddress=S10.142.33.235:11111:125510942 SiloName=app-56c9d6644c-txwvl Status=Dead, 
SiloAddress=S10.142.36.50:11111:125580330 SiloName=app-6d756f64bb-6q4tz Status=Dead, 
SiloAddress=S10.142.36.246:11111:124806027 SiloName=app-5c8f976684-qqpc4 Status=Dead, 
SiloAddress=S10.142.33.189:11111:125511045 SiloName=app-56c9d6644c-t6hrz Status=Dead, 
SiloAddress=S10.142.35.160:11111:125591496 SiloName=app-5547f98bdc-kc24d Status=Active, 
SiloAddress=S10.142.38.156:11111:125519460 SiloName=app-6cbc9f7f-ksvl5 Status=Dead, 
SiloAddress=S10.142.36.80:11111:125519545 SiloName=app-6cbc9f7f-8xt9g Status=Dead, 
SiloAddress=S10.142.36.23:11111:125510995 SiloName=app-56c9d6644c-wlv7g Status=Dead, 
SiloAddress=S10.142.36.74:11111:125580448 SiloName=app-6d756f64bb-hvjds Status=Dead, 
SiloAddress=S10.142.34.28:11111:125510959 SiloName=app-56c9d6644c-w7xzt Status=Dead, 
SiloAddress=S10.142.36.117:11111:125591576 SiloName=app-5547f98bdc-x5q4z Status=Active, 
SiloAddress=S10.142.34.84:11111:125519494 SiloName=app-6cbc9f7f-qpnb4 Status=Dead, 
SiloAddress=S10.142.33.172:11111:125591596 SiloName=app-5547f98bdc-wwkkx Status=Active, 
SiloAddress=S10.142.34.24:11111:124806048 SiloName=app-5c8f976684-jzwjc Status=Dead, 
SiloAddress=S10.142.36.0:11111:124806078 SiloName=app-5c8f976684-sdfrp Status=Dead, 
SiloAddress=S10.142.36.0:11111:125519444 SiloName=app-6cbc9f7f-tvnww Status=Dead, 
SiloAddress=S10.142.33.145:11111:125510890 SiloName=app-56c9d6644c-xg552 Status=Dead, 
SiloAddress=S10.142.36.134:11111:125580405 SiloName=app-6d756f64bb-hm7r7 Status=Dead, 
SiloAddress=S10.142.33.165:11111:125510890 SiloName=app-5c8f976684-svwxw Status=Dead, 
SiloAddress=S10.142.35.245:11111:124805964 SiloName=app-5c8f976684-bhttz Status=Dead, 
SiloAddress=S10.142.38.190:11111:125591544 SiloName=app-5547f98bdc-sqdtb Status=Active, 
SiloAddress=S10.142.33.143:11111:124806011 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.143:11111:125402340 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.143:11111:125402622 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.143:11111:125402860 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.143:11111:125403325 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.143:11111:125403572 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.143:11111:125404111 SiloName=app-5c8f976684-l4qzk Status=Dead, 
SiloAddress=S10.142.33.167:11111:125580419 SiloName=app-6d756f64bb-bwpch Status=Dead, 
SiloAddress=S10.142.32.239:11111:125519529 SiloName=app-6cbc9f7f-wpmzd Status=Dead, 
SiloAddress=S10.142.36.146:11111:124806065 SiloName=app-5c8f976684-9mlg6 Status=Dead, 
SiloAddress=S10.142.33.237:11111:125404360 SiloName=app-5c8f976684-bjlnn Status=Dead, 
SiloAddress=S10.142.35.137:11111:125519560 SiloName=app-6cbc9f7f-6qc2s Status=Dead, 
SiloAddress=S10.142.33.93:11111:125591512 SiloName=app-5547f98bdc-8472t Status=Active, 
SiloAddress=S10.142.35.207:11111:124805980 SiloName=app-5c8f976684-bcht5 Status=Dead, 
SiloAddress=S10.142.35.194:11111:125519413 SiloName=app-6cbc9f7f-6wtnk Status=Dead]
```

**Comment by ReubenBond** [comment]
That certainly looks suspicious. Just to be sure, is the grain a stateless worker?

**Comment by ReubenBond** [comment]
Here are some hypotheses:
* In a previous 9.1.x release, there was a hash code generation bug which caused inconsistencies across the cluster (but you said you're running v9.2.1, where that bug was already fixed)
* Different hosts are seeing different views of the cluster somehow. This should not be possible if you're using Azure Storage Clustering and have all hosts configured identically (same ServiceId and same ClusterId). Please double check that. When you say you are using Azure Storage for clustering, I assume it's actual Azure Storage tables and not another service which exposes Azure Storage APIs (eg, Cosmos DB, which could potentially be configured to use geo replication which may not be strongly consistent).
* A bug in the directory implementation. This is possible. The "guarantee" that the default directory provides is eventual consistency: there may be duplicate activations for a short period of time, but they should converge to a single activation quickly. It's possible that there is a race or some other issue preventing directory convergence. The new grain directory (see above comment) offers linearizability - there is no room for divergence among the active hosts in the cluster. Hosts which have recently been evicted from the cluster (but are actually still alive - just thought to be down) might still be actively running grain activations that have been activated elsewhere after the host was evicted. It's possible that you are seeing that case, but if you were then it would be short lived: hosts detect that they have been evicted when they periodically refresh membership and when they do, they promptly terminate.

**Comment by MaximTkachenko** [comment]
@ReubenBond I enabled `DistributedGrainDirectory` five days ago, and no duplicates have been detected since then. 👍
What is the default directory implementation used when `DistributedGrainDirectory` is not enabled?


Also I still have a gap in my mental model of what Orleans guarantees with regard to persistence. You wrote that `hosts … might still be actively running grain activations that have been activated elsewhere after the host was evicted.` So the following flow is confusing to me:
- cluster has three silos: `silo_1`, `silo_2`, and `silo_3`;
- `silo_3` has activation `AAA_1` for grain `AAA`;
- `silo_3` is marked as dead by `silo_1` and `silo_2`;
- a new message for `AAA` arrives, and `silo_1` creates a new activation `AAA_2`;
- `AAA_1` has an internal timer that updates the persistent state;
- `silo_3` is eventually forced to shut down;
- `AAA_2` now has outdated state now.

Is this understanding correct?

**Comment by MaximTkachenko** [comment]
Update: After switching to [DistributedGrainDirectory](https://learn.microsoft.com/en-us/dotnet/api/orleans.hosting.corehostingextensions.adddistributedgraindirectory?view=orleans-9.1) (we're still on .NET 9), this issue disappeared.

Since @ReubenBond mentioned it will become the default in the future and provides stricter guarantees, I’ve closed this issue.

That said, it’s still not clear to me what caused this behavior when our cluster was running the DHT grain directory.
